name: Github Arduino Library CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1
      with:
        python-version: '3.x' # Version range or exact version of a Python version to use, using semvers version range syntax.
        architecture: 'x64' # optional x64 or x86. Defaults to x64 if not specified
    - name: pre-install
      run: |
        source install.sh
    - name: test platform
      run: |
        ./install.sh build_platform esp32
        ./install.sh build_platform uno
        ./install.sh build_platform leonardo
        ./install.sh build_platform zero
        ./install.sh build_platform esp8266
        ./install.sh build_platform m4
        ./install.sh build_platform nrf52840

